language: python
python:
  - "2.7"
# dependencies
install:
  - pip install jupyter
  - pip install ipython
  - pip install traitlets
  - pip install requests
  - pip install notebook
# command to run tests
script: python -m unittest discover
