language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
sudo: false
cache:
  directories:
  - "~/.cache/pip"
install:
  - pip install tox codecov
script:
  - tox -v -e py
after_success:
  - codecov
